import { useState } from 'react'
import { Radio, Shield, Signal } from 'lucide-react'

const RADIO_CODES = [
  ['10-01', 'Telsiz deneme.', 'red'], ['10-02', 'Telsiz sinyali iyi (telsiz denemesi sonrası).', 'red'], ['10-03', 'Telsiz iletişimi sonu (iletişim kesiliyor).', 'orange'], ['10-04', 'Anlaşıldı (olumlu).', 'red'], ['10-05', 'Anlaşılmadı.', 'red'], ['10-06', 'Son anons iptal.', 'orange'], ['10-07', 'Asılsız ihbar.', 'orange'], ['10-09', 'Beni telefonla ara.', 'green'], ['10-10', 'Mesai girişi.', 'red'], ['10-11', 'Mesai çıkışı.', 'red'], ['10-12', 'Devriye başlangıcını bildiriyorum.', 'red'], ['10-13', 'Devriye sonu bildiriyorum.', 'red'], ['10-17', 'Devriyedeki birimler (hava – yol) rapor verin.', 'red'], ['10-18', 'Rapor veriyorum.', 'red'], ['10-19', 'Tüm birimler departmana geri dönün.', 'red'], ['10-20', 'Merkez departmana intikal (ör. A3 10-20).', 'red'], ['10-21', 'Nakil veya transfer anında konvoy veya eskort durumu.', 'green'], ['10-22', 'Sağlık birimlerine haber verin.', 'orange'], ['10-23', 'İntikal ediyorum.', 'red'], ['10-26', 'Bölgeye süpervizör talebim mevcut.', 'green'], ['10-30', 'Agresif araç takibi.', 'red'], ['10-44', 'Aranan araç/şahıs görüldü.', 'green'], ['10-45', 'Olay sona erdi / görüş yok.', 'green'], ['10-49', 'Yol üzeri araç tamiri (ör. A3 10-49).', 'green'], ['10-50', 'Trafik kazası durumu.', 'orange'], ['10-58', 'Yakınımda bir birim beklesin.', 'green'], ['10-60', 'Kavga dövüş durumu (bir araya gelmiş kalabalık grup).', 'green'], ['10-70', 'Destek birim gerekiyor.', 'orange'], ['10-71', 'Destek birim gerekmiyor.', 'orange'], ['10-75', 'Çevre güvenliği.', 'red'], ['10-80', 'Pull over durumu.', 'red'], ['10-91', 'Gelip şüpheliyi teslim alın.', 'green'], ['10-97', 'Motorlu birim ihtiyacım mevcut.', 'orange'], ['10-98', 'HSU birim ihtiyacım mevcut.', 'orange'], ['Kod-0', 'Yaralı memur.', 'red'], ['Kod-1', 'Rutin çağrı siren ve çakar kapalı.', 'red'], ['Kod-2', 'Öncelikli çağrı siren kapalı, çakar açık.', 'red'], ['Kod-3', 'Acil çağrı, siren ve çakar açık.', 'red'], ['Kod-4', 'Aktif devriyemize devam ediyoruz (ör. A3 KOD 4).', 'red'], ['Kod-6', 'Görev ve rutin kontrol için araçtan iniş.', 'red'], ['Kod-7', 'İhtiyaç molası/AFK.', 'red'], ['Kod-8', 'Çağrılara açığız (ör. A3 KOD 8).', 'red'], ['Kod-77', 'Olası pusu durumu.', 'red'], ['Kod-99', 'Sorgulama/oyun hatası.', 'red'],
]

const UNIT_CODES = [
  ['Adam (A)', 'Çift kişilik saha devriyesidir.', 'Devriye Birimi', 'Memur I rütbesinde Adam devriyeye çıkabilirsiniz.'],
  ['Lincoln (L)', 'Tek kişilik saha devriyesidir.', 'Devriye Birimi', 'Memur II rütbesinden sonra Lincoln devriyesine çıkabilirsiniz.'],
  ['Mary (M)', 'Motorsiklet devriyesidir.', 'Devriye Birimi'],
  ['Tom (T)', 'Trafik birimi devriyesidir.', 'Trafik Birimi'],
  ['David (D)', 'SWAT devriyesidir.'],
  ['Rescue (R)', 'SWAT birimleri olarak operasyona gidildiğinde kullanılır.'],
  ['Queen (Q)', 'Özel yetkili ve görev tanımlaması olmayan devriyedir.'],
  ['William (W)', 'Dedektif devriyesidir.', 'Devriye Birimi'],
  ['Omega (O)', 'Üç veya daha fazla kişiyle yapılan saha devriyesidir.', 'Devriye Birimi'],
]

const tone = { red: 'text-rose-300 bg-rose-400/10 border-rose-400/20', orange: 'text-orange-300 bg-orange-400/10 border-orange-400/20', green: 'text-emerald-300 bg-emerald-400/10 border-emerald-400/20' }
const TEN_CODES = RADIO_CODES.filter(([code]) => code.startsWith('10-'))
const STATUS_CODES = RADIO_CODES.filter(([code]) => code.startsWith('Kod-'))

function RadioCodeList({ title, codes }) {
  return <section className="overflow-hidden rounded-2xl border border-slate-800 bg-[#0d1626]"><div className="border-b border-slate-800 px-5 py-4"><h3 className="font-bold text-white">{title}</h3><p className="mt-1 text-xs text-slate-500">{codes.length} kod</p></div><div className="grid gap-px bg-slate-800 sm:grid-cols-2">{codes.map(([code, description, color]) => <article key={code} className="flex items-start gap-3 bg-[#0d1626] px-4 py-3 sm:px-5"><span className={`min-w-[68px] rounded-md border px-2 py-1 text-center font-mono text-sm font-bold ${tone[color]}`}>{code}</span><p className={`text-sm leading-6 ${color === 'red' ? 'text-rose-200' : color === 'orange' ? 'text-orange-200' : 'text-emerald-200'}`}>{description}</p></article>)}</div></section>
}

export default function CodesPanel() {
  const [section, setSection] = useState('radio')
  return <main className="mx-auto max-w-[1200px] px-4 py-7 sm:px-6">
    <header className="mb-6 rounded-3xl border border-slate-700/80 bg-gradient-to-br from-[#162847] via-[#101b2e] to-[#0d1626] p-6 sm:p-8"><div className="flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl border border-sky-300/20 bg-sky-400/10 text-sky-300"><Radio className="h-7 w-7" /></div><div><p className="text-[10px] font-bold uppercase tracking-[0.25em] text-[#c9a24b]">LSPD · HIZLI REFERANS</p><h2 className="mt-1 text-2xl font-bold text-white">Kodlar</h2><p className="mt-1 text-sm text-slate-400">Birim ve telsiz kodlarına buradan ulaşabilirsiniz.</p></div></div></header>
    <div className="mb-5 flex flex-wrap gap-2" role="tablist" aria-label="Kod kategorileri"><button role="tab" aria-selected={section === 'units'} onClick={() => setSection('units')} className={`inline-flex items-center gap-2 rounded-xl border px-4 py-3 text-sm font-bold transition ${section === 'units' ? 'border-sky-400/40 bg-sky-400/10 text-sky-200' : 'border-slate-700 bg-slate-900 text-slate-400 hover:text-white'}`}><Shield className="h-4 w-4" />Birim kodları</button><button role="tab" aria-selected={section === 'radio'} onClick={() => setSection('radio')} className={`inline-flex items-center gap-2 rounded-xl border px-4 py-3 text-sm font-bold transition ${section === 'radio' ? 'border-amber-400/40 bg-amber-400/10 text-amber-200' : 'border-slate-700 bg-slate-900 text-slate-400 hover:text-white'}`}><Signal className="h-4 w-4" />Telsiz kodları</button></div>
    {section === 'units' ? <section className="grid gap-3 md:grid-cols-2">{UNIT_CODES.map(([code, description, unit, note]) => <article key={code} className="rounded-2xl border border-slate-800 bg-[#0d1626] p-5"><div className="flex items-start justify-between gap-3"><h3 className="text-lg font-bold text-white">{code}</h3>{unit && <span className="rounded-full border border-sky-400/20 bg-sky-400/10 px-2.5 py-1 text-[10px] font-bold uppercase tracking-wide text-sky-200">{unit}</span>}</div><p className="mt-3 text-sm leading-6 text-slate-300">{description}</p>{note && <p className="mt-3 rounded-lg border border-amber-400/15 bg-amber-400/[0.06] p-3 text-xs leading-5 text-amber-200">{note}</p>}</article>)}</section> : <div className="grid items-start gap-5 lg:grid-cols-[minmax(0,1fr)_280px]"><div className="space-y-5"><RadioCodeList title="10 kodları" codes={TEN_CODES} /><RadioCodeList title="Kod-0–Kod-99" codes={STATUS_CODES} /></div><aside className="rounded-2xl border border-slate-800 bg-[#0d1626] p-5 lg:sticky lg:top-24"><div className="flex items-center gap-2"><Signal className="h-5 w-5 text-amber-300" /><h3 className="font-bold text-white">Renk açıklaması</h3></div><p className="mt-1 text-xs text-slate-500">Kodların kullanım sıklığı</p><ul className="mt-5 space-y-3"><li className="flex items-center gap-3 rounded-xl border border-rose-400/15 bg-rose-400/[0.06] p-3"><span className="h-3 w-3 shrink-0 rounded-full bg-rose-400" /><span className="text-sm font-semibold text-rose-200">Kırmızı <span className="font-normal text-slate-300">– En fazla kullanılan</span></span></li><li className="flex items-center gap-3 rounded-xl border border-orange-400/15 bg-orange-400/[0.06] p-3"><span className="h-3 w-3 shrink-0 rounded-full bg-orange-400" /><span className="text-sm font-semibold text-orange-200">Turuncu <span className="font-normal text-slate-300">– Ortalama kullanılan</span></span></li><li className="flex items-center gap-3 rounded-xl border border-emerald-400/15 bg-emerald-400/[0.06] p-3"><span className="h-3 w-3 shrink-0 rounded-full bg-emerald-400" /><span className="text-sm font-semibold text-emerald-200">Yeşil <span className="font-normal text-slate-300">– Az kullanılan</span></span></li></ul></aside></div>}
  </main>
}
